nationalarchives/tdr-jenkins

- terraform/root.tf
Add common tag for CostCentre so that Digital Services can identify our resources in the organisation's AWS bill.
> Add CostCentre tag to all resources

- docker/plugins.txt
Add plugin which lets us use SSH to connect to GitHub. This makes it easier to push updates like tags and environment-specific branches from Jenkins builds.
> Add ssh-agent plugin

- docker/jenkins.yml
This makes it easier to let Jenkins jobs to push changes back to github.
Jenkins clones the repo using the public URL, which you can only push change to if you are using an SSH key for authentication. Pushing changes with a password would require you to add the username and password to the git URL.
> Replace github username and password with SSH key

- docker/jenkins.yml
Remove users who have left TNA or who do not need access to Jenkins.
> Remove Jenkins admin users

- terraform/modules/jenkins/network.tf
AWS automatically creates a default security group with each VPC, which can't be deleted. This change brings the default security group under Terraform management and removes all rules.
> remove rules from default security group

- terraform/modules/jenkins/ecs.tf
This token is used to publish JavaScript libraries built by Jenkins.
> Give Jenkins permission to read npm_token parameter

- terraform/modules/jenkins/ecs.tf
- terraform/modules/jenkins/templates/jenkins.json.tpl
This directory contains Jenkins dependencies like plugins, build definitions and build histories.
This directory was originally mounted from the EC2 instance so that we could preserve its contents between ECS container deployments. This turned out not to be sufficient, so we then added a backup restore process which restores the build history to the container when it starts up.
This means that the EC2 directory mount is no longer necessary, because the container gets all of the Jenkins configuration from the combination of the image and the restored backup.
> Remove /var/jenkins_home mount from Jenkins container

- docker/jenkins.yml
The `adminAddress` value has been deprecated: https://github.com/jenkinsci/mailer-plugin/blob/62f0d0fa7c58f651d898f656b7e9b7c12011fe95/src/main/java/hudson/tasks/Mailer.java#L278
When we tried to upgrade the Jenkins plugins, it failed with the error:
```
2020-04-17 13:54:31.521+0000 [id=26]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
io.jenkins.plugins.casc.ConfiguratorException: 'adminAddress' is deprecated
...
Caused: io.jenkins.plugins.casc.ConfiguratorException: unclassified: error configuring 'unclassified' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
```
From that documentation, it looks like the `adminAddress` in the `mailer` section has been deprecated in favour of the one in the …
> Remove deprecated adminAddress config value

- terraform/root.tf
Increase the unhealthy check threshold from the default (2) to 5. This is the number of times that a healthcheck has to fail before ECS deploys a new container.
Healthchecks currently run every 30 seconds. The previous limit meant that the Jenkins container would be redeployed if Jenkins didn't response to the healthcheck within a minute. That meant that we couldn't soft-restart the Jenkins service, which takes around 90 seconds to restart.
Increasing this threshold means that Jenkins might be down for a few minutes before ECS tries to resolve the problem, but we don't expect that to be a big problem because Jenkins is developer-facing and we'll be able to investigate any problems that arise in practice.
Depends on a change to the modules repo: …
> Increase the health check threshold

- docker/jenkins.yml
This will let us update the GitHub branch status based on the Jenkins build output.
https://national-archives.atlassian.net/browse/TDR-142
> Add credentials for Jenkins API key

- terraform/modules/jenkins/ecs.tf
This API key is used to report the status of Jenkins branch builds to GitHub.
> Give Jenkins permission to read GitHub API key

- docker/aws/deploy_lambda_from_s3.py
- docker/aws/update_event_mapping.py
If we want to be able to roll back or deploy changes from a specific
branch, then we need the event source mapping to be separate, so we can
point the sqs queue to a specific version of the code.
> Split out event mapping scripts.

- docker/jenkins.yml
This is with added credentials, but these may not be needed as the jenkinslib repo is public. 
This change facilitates the use of our new jenkinslib of functions so we can utilise groovy functions across all TDR Jenkins jobs and keep code DRY.
This was done with help from @TomJKing
> Add link to shared jenkinslib repo

- docker/jenkins.yml
Missing default branch for global library
Remove credentials as not needed as library is public
Add implicit load option so @Library annotation is not needed in groovy scripts to import the library
> Add default branch to config

- docker/jenkins.yml
Jenkins URL incorrectly configure to old prototype URL
Causing issues with environment variables such as BUILD_URL which pointed to the old URL
> Fix Jenkins URL configuration

- terraform/modules/jenkins/flowlogs.tf
- terraform/modules/jenkins/outputs.tf
- terraform/root.tf
Stream VPC flowlogs directly to S3, and remove the Kinesis Firehose stream from CloudWatch logs to S3.
This ensures the logs arrive in S3 in a format compatible with Athena searches.
> Flow logs to S3

- docker/jenkins.yml
This is to allow for Jenkins builds within our Jenkins space to explicitly import the Jenkinslib, making it clearer which Jenkinslib you are dealing with (if using a branch to test). It also allows for a clearer view of the relationship between the Jenkinslib and Jenkins pipelines.
> Remove jenkinslib implicit loading.

- terraform/modules/jenkins/ec2.tf
This technically should only be temporary until the other az in eu-west-2 is up and running but I've had to change a load of system parameters and the like to get it working so we may as well make it permanent.
> Move jenkins to a new subnet

- docker/aws/Dockerfile
- terraform/modules/jenkins/iam.tf
- terraform/modules/jenkins/templates/s3publish.json.tpl
- terraform/modules/s3-publish-build-task/ecs.tf
- terraform/root.tf
We don't use these directly so I forgot about them.
One is the base image with python3.7 we use for AWS and one is the image
we use for the database migrations.
> Add missing repositories to ECR

- docker/jenkins.yml
- docker/plugins.txt
- terraform/modules/jenkins/iam.tf
- terraform/modules/jenkins/templates/assume_role_policy.json.tpl
The aws-credentials plugin that we use to store the credentials for the ECS plugin allow you to specify a role in place of an access key and secret key. 
This sets up the role and configures jenkins to use it. This means that we can get rid of the jenkins-ecs IAM user.
> Use role for ecs plugin

- docker/jenkins.yml
authenticatedUserReadPermission was allowing anyone with a github account to see the Jenkins jobs so this can be disabled.
The other two weren't causing problems as such but we don't need them so we may as well switch them off.
> Set access permissions to false

- docker/backup.sh
Healtcheck.io will alert us if this url isn't pinged at least once a day
by this script.
The $1 argument here is the healthcheck url which is passed in through
terraform.
> Add call to healthcheck.io

- docker/sbt/Dockerfile
The database migration publish job was failing because it couldn't find
the sbt-launch.jar file. I don't know why this doesn't affect the front
end build because those docker files are identical in terms of
installing sbt but there you go.
I've added another symlink to the launch jar and the build is working
now.
> Add symlink to launch jar.

- README.md
- terraform/modules/jenkins/ec2.tf
- terraform/modules/jenkins/variables.tf
- terraform/root.tf
- terraform/root_data.tf
- terraform/root_locals.tf
- terraform/root_provider.tf
Use AWS Systems Manager Maintenance Window to set up a daily Jenkins backup.
This commit moves the Maintenance Windows config from tdr-terraform-backend (https://github.com/nationalarchives/tdr-terraform-backend/pull/82) into this repo.
Configuring it in the backend repository caused a problem whenever the Jenkins EC2 instance was redeployed, because the maintenance window is linked directly to the EC2 _instance_ ID. This meant that when you deploy the Jenkins EC2 instance, the backups fail because the maintenance windows tries to run the backups on the old instance.
Moving the configuration to the tdr-jenkins repo should fix the issue because we deploy a new EC2 instance by running the tdr-jenkins Terraform script. This should update link between the maintenance window and the EC2 …
> Configure Jenkins backups

- terraform/root.tf
This forces the module to wait for the EC2 instance to be created, which means the maintenance task is run on the latest version of the instance.
This fixes a bug where the EC2 instance was updated, but Terraform couldn't tell that the instance ID needed to be updated to match.
Depends on https://github.com/nationalarchives/tdr-terraform-modules/pull/71 being merged.
> Pass EC2 instance ID instead of name to maintenance window module

- README.md
Explain how to deploy Jenkins to ECR, since we have migrated all our Docker images to there.
Also add a note reminding people to restart the ECS service after pushing a new image, and update the default base image for Docker nodes in the Readme.
> Replace Docker Hub instructions with ECR

- terraform/modules/jenkins/iam.tf
This is the task role for jenkins. It needs permission to be able to
pass the consignment export role used by the e2e tests to the node
container.
> Allow Jenkins to assume export role

- docker/jenkins.yml
The e2e tests need to assume a role in the intg/staging accounts in
order to check the consignment export s3 bucket. The sts sdk uses the
arn for the role which means we need the account number. It's easiest to
get these from the environment variables so I've added them to the
container here.
> Add accounts to the frontend container

- terraform/root.tf
This is the command for the jenkins backup which is run on the ec2
instance against the jenkins docker container. The command as was works
if there is only one jenkins container but if jenkins has been restarted
recently, there can be old, stopped containers and trying to run docker
exec on these doesn't work.
So we need to filter out the non-running containers.
> Filter only running images

- docker/transfer-frontend/Dockerfile
We need gnu tar to run the tests for the consignment export as the
version that comes with alpine is missing a lot of features that we're
using. This adds it to the image.
> Add gnu tar

- terraform/modules/jenkins/ec2.tf
The jenkins docker container is now running as the jenkins user rather than root. This user is in the docker group but it's still not able to run docker commands. I think this is because the /var/run/docker.sock and /var/run/docker/ are owned by root on the host machine so the docker container can't access them. This changes permissions on the docker.sock and docker directory which allows the jenkins user to access them.
> Change owner to user 1000 for /var/run/docker*

- docker/aws/Dockerfile
- docker/npm/Dockerfile
- docker/sbt/Dockerfile
- docker/terraform/Dockerfile
- docker/transfer-frontend/Dockerfile
The jenkins/jnlp-slave image has been deprecated and replaced by jenkins/inbound-agent. See https://github.com/jenkinsci/docker-inbound-agent
The latest version of both images was published two months ago, so they might be identical at the moment anyway.
> Update base image of build nodes

- docker/npm/Dockerfile
The version in the Jenkins base image is out-of-date.
> Upgrade OpenSSL in the npm build node

- README.md
- Add reminder to run a backup first
- Explain how to fix the deployment if there are not enough resources available on EC2
> Make Jenkins ECS deployment instructions clearer

- docker/sbt/Dockerfile
There is a security vulnerability on the version on the jenkins base
image. This will be fixed by jenkins eventually but for now, we'll
upgrade it manually.
> Upgrade musl

- README.md
The jenkins/jnlp-slave Docker image has been renamed to jenkins/inbound-agent. See deprecation warning in https://hub.docker.com/r/jenkins/jnlp-slave
> Update default base node image in Readme

- terraform/root.tf
This Jenkins node image is no longer used. It was necessary when the latest version of Python 3 was unavailable in the Jenkins node base image, but that was updated recently so this ECR repo is no longer necessary.
> Remove Python build node image repository

- terraform/root.tf
The ECR module adds this URL to an AWS tag on the ECR repo, to make it easier to find the Docker image source.
> Add link from each ECR repo to image Dockerfile

- terraform/root.tf
- terraform/root_data.tf
This was originally in the terraform-backend project but it's been moved here so that the instance id will update when we rebuild the jenkins ec2 instance.
> Add the maintenance cloudwatch event.

- docker/npm/Dockerfile
- docker/transfer-frontend/Dockerfile
Dependabot upgraded the minify package but this new package doesn't work with the older versions of node we were using so I've updated them both to the latest version.
> Upgrade node

- docker/aws/Dockerfile
The antivirus build uses this image and the latest version of the cryptography library that is uses needs rust installed.
> Install rust to the aws docker image

- docker/Dockerfile
- docker/entrypoint.sh
If it's configured in the build as it was, the global ~/.gitconfig file is not created for some reason I don't know. If we move these commands to the entrypoint script, it works and creates the correct file.
> Move git secrets config to entrypoint

- docker/jenkins.yml
I missed a script approval for the e2e tests check to work, I've added it in here.
> Add missing script approval

- docker/backup.sh
- terraform/modules/jenkins/ec2.tf
- Stream backup file straight to s3
- Give the jenkins box 60Gb disk
> Jenkins disk space fixes

- docker/postgres/Dockerfile
This will fix a current vulnerability but also this is a common source of vulnerabilities so it makes sense to have it in the dockerfile and we can fix it by running the docker build again.
> Add line to upgrade openssl

- terraform/modules/jenkins/templates/s3publish.json.tpl
- terraform/modules/sbt-with-postgres-task/ecs.tf
- terraform/root.tf
This was called s3Publish but now I want to use it for the database user creation lambda tests so I've renamed it to something a bit more generic.
> Rename jenkins node task definition

- docker/jenkins.yml
Allow members of the TDR admin team to manage Jenkins, but remove those permissions from the main dev team.
This still allows devs to deploy to all environments, which we might revisit in another change.
This draft PR while we test the changes.
> Remove Jenkins admin permissions from dev team

- .gitignore
- README.md
- terraform/modules/jenkins/security.tf
- terraform/modules/jenkins/variables.tf
- terraform/root.tf
- terraform/root_locals.tf
This changes where the list of IPs which are allowed to access Jenkins is read from.
Before, we read the list from a parameter in the AWS SSM Parameter Store. Now, it reads the list from the [tdr-configurations](https://github.com/nationalarchives/tdr-configurations) repo.
The tdr-configurations repo was already being used for the frontend load balancer allow list, so this change makes Jenkins consistent with [tdr-terraform-environments](https://github.com/nationalarchives/tdr-terraform-environments).
It also reduces the number of deployment steps. When the list changes, we can now deploy the changes by running this Terraform project, without having to deploy the change to the parameter store first.
> Fetch IP allow list from tdr-configurations instead of SSM param

- docker/jenkins.yml
The GitHub team has been deleted, so this is no longer necessary.
> Remove pen test team from permissions list

- docker/jenkins-prod.yml
- docker/jenkins.yml
This is needed for prod jenkins which runs the acceptance tests for
staging but isn't needed in integration jenkins so I've swapped them
over.
> Move STAGING_AWS_ACCOUNT_NUMBER variable.

- terraform/root_locals.tf
Add `TerraformSource` tag which links to this code repo. This will make it easier for devs to find the Terraform source which created a particular resource in the AWS console.
> Add new default tag for Terraform source

- docker/plugins.txt
The pen test found that this was missing, this plugin adds it back in
> This plugin adds the strict-transport-security header

- README.md
This looks like it was a copy-paste error rather than an intentional character.
> Delete invalid backtick from Docker build examples

- README.md
The recent backup history is a single list which combines both Jenkins instances, so you have to open individual commands to make sure you're rerunning a backup of the intended instance.
> Distinguish between jenkins and jenkins-prod in backup instructions

- docker/jenkins.yml
I'm using a slack webhook to send updates about out of date versions and
we would like to send this to the release channel. We don't currently
have a webhook for the release channel. I've added the parameter into
SSM manually and this will add it into the Jenkins instance.
We don't need this for prod Jenkins as the job will only run on the
integration Jenkins.
> Add secret for slack release channel webhook.

- docker/aws/Dockerfile
The version of botocore which the c7n dependencies need is older than
the ones used by awscli and boto3 and they're incompatible so we need to
do this while cloud custodian upgrade their dependencies.
> Pin dependencies for awscli and boto3

- docker/transfer-frontend/Dockerfile
One of the latest updates to alpine seems to have removed the xz install
by default so when you try to do `tar -xz` it fails. Adding this lets
you build the docker image.
> Install xz

- docker/terraform/Dockerfile
The terraform-v13 image node will be retained until all Jenkins jobs are pointed back to the main terraform image node
Draft until `tna-custodian` repo upgraded.
> Upgrade main terraform image to v13

- docker/plugin-updates/Jenkinsfile
The job was failing if there were changes because the command returns
status code 1. Using returnStatus means the job will report the exit
code without failing.
> Return status instead of stdout

- docker/nodes/plugin-updates/Dockerfile
We have changed the build process so we build all of the node images
from the nodes directory and use `-f <node_name>/Dockerfile` in the
build command. This copy command was copying the contents of the nodes
directory instead of the plugin-updates directory it was supposed to so
this corrects it.
> Copy from the plugin-updates directory.

- docker/nodes/aws/Dockerfile
There are dependency problems between aws cli v1 and the other
dependencies that use botocore.
It seems the easiest is to install aws cli v2. I've looked at the places
we're using it and tried out a couple of builds that use it and it looks
ok.
> Use aws cli version 2

- Jenkinsfile-build-nodes
To avoid having duplicate image tag of "jenkins-prod:latest" when building the Jenkins prod image node on the Jenkins prod instance, use version number as the tag, then retag the pushed image on ECR with the "latest".
Having a duplicate image tag causes Docker to untag the earlier image, ie the image which the Jenkins prod container is built from. This means that Jenkins prod container references the image id instead of the tag. This causes the Jenkins backup script to fail as the script looks for the container using the image tag, which is no longer referenced by the running container.
> Tag Jenkins node images with version number

- docker/nodes/postgres/Dockerfile
The latest jenkins/inbound-agent:alpine is causing an error with sbt. Appears to be related that the latest alpine is using Java 11 which is incompatible with sbt: https://github.com/sbt/sbt/issues/3804#issuecomment-761830689
Ensure use alpine with JDK8
> Pull latest JDK8 image

- terraform/root_common.tf
- terraform/root_integration.tf
- terraform/root_locals.tf
- terraform/root_production.tf
Add modules for disk space alerting. 
* An SSM parameter for the cloudwatch agent config
* A mgmt notifications topic to send the alerts to slack
* A policy to allow the EC2 instance agent to push to cloudwatch
* A cloudwatch alarm for each Jenkins instance which will alert when the disk space is full.
> Disk space alerts

- docker/Dockerfile
- docker/Dockerfile-prod
There is a vulnerability on libgrypt but we can't upgrade Jenkins until
we've changed our builds to say controller instead of master so we need
to upgrade the package instead.
> Upgrade libgrypt

- docker/Dockerfile
- docker/Dockerfile-prod
- docker/plugins.txt
My changes to the github oauth plugin have been merged and a new release produced so we should now be able to use the official version of the plugin.
> Stop using patched oauth plugin

- Jenkinsfile-scheduled-node-build
- README.md
- docker/jenkins.yml
Add Jenkinsfile to rebuild node images.
This will be run on a schedule. This is to try and stop the vulnerabilities we're getting every other week. 
I've left the jenkins images themselves as they're updated manually when there are plugin or version updates.
> Rebuild nodes on a schedule

- terraform/root_data.tf
- terraform/root_integration.tf
- terraform/root_production.tf
Changes already deployed and Terraform state manually updated to remove references to the hosted zones
The hosted zones are created within the tdr-aws-accounts Terraform
Jenkins Terraform was inadvertently overwriting the hosted zones
Set parameter 'create_host_zone' to false to prevent this happening in the future
The hosted zone AWS resource needs to be manually removed from the Jenkins Terraform state file, to prevent deletion of the existing hosted zone AWS resource
> Prevent Jenkins terraform creating hosted zone

- docker/Dockerfile
- docker/Dockerfile-prod
There are two CVEs for this library
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-23852
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-23990
The upgrade has fixed the vulnerability. This has already been deployed.
> Upgrade expat.
