- README.md
- docker/plugins.txt
Also add missing Docker tag in README
> Fix version number of Cucumber reports plugin

- docker/aws/Dockerfile
Add --upgrade and --user options to AWS cli pip install
> Install AWS cli with default settings

- docker/jenkins.yml
Increase memory and CPU for AWS container, to avoid issues deploying Cloud Custodian
> Increase resources for AWS container

- docker/jenkins.yml
Also removes colleague not on TDR from TDR jenkins.
> Adds Loki as Jenkins admin to faciliate changes to jenkins setup.

- docker/plugins.txt
Remove plugins that we don't use in any builds, and that don't seem to be depended on by any other plugins.
> Delete unused plugins

- docker/jenkins.yml
> Remove Paul Schwarzenberger from access list

- docker/sbt/Dockerfile
This will let us run pg_dump in the consignment-api-data repo.
> Add postgres dependency and pgpass file.

- docker/npm/Dockerfile
- docker/terraform/Dockerfile
- docker/transfer-frontend/Dockerfile
Pre-defined user already available without root user privileges
> Use pre-defined jenkins user

- docker/plugins.txt
Some of these were stopping jenkins from starting so I've upgraded them.
> Upgrade plugins to the latest version

- docker/plugin-updates/Jenkinsfile
I've stopped trying to create a PR on a deleted branch and I've added a
post failure step so we'll get a notification when it fails.
> Fixes for the plugin updates Jenkinsfile

- terraform/jenkins_terraform_v13_node.tf
Requires PR: https://github.com/nationalarchives/tdr-terraform-modules/pull/118
> Attach Terraform v13 policies to ECS execution role

- docker/aws/modify_alb_listener.py
This is used for deploying the service unavailable page. The load
balancer listener is changed to point to the service unavailable target
group.
> Add script to modify alb listener.

- docker/plugin-updates/Jenkinsfile
`git diff --exit-code docker/plugins.txt` will return 1 if there are
changes and 0 if not so we only go through with creating a branch etc if
there are changes.
If there are none, it sends a slack message to say that it didn't have
any updates.
> Check for changes to plugins.txt before trying to create PR

- Jenkinsfile-build-nodes
- README.md
- docker/jenkins-prod.yml
- docker/jenkins.yml
- terraform/root_data.tf
- terraform/root_production.tf
Requires PRs:
- https://github.com/nationalarchives/tdr-terraform-modules/pull/135
- https://github.com/nationalarchives/tdr-scripts/pull/24
> Tdr 1001 build jenkins nodes

- docker/Dockerfile
Issue with Jenkins builds following clean up of node names in version 2.307:https://www.jenkins.io/changelog/
> Downgrade jenkins version

- docker/Dockerfile-prod
Issue with Jenkins builds following clean up of node names in version 2.307:https://www.jenkins.io/changelog/
> Fix Jenkins version at 2.306

- Jenkinsfile-check-versions
- docker/nodes/plugin-updates/Dockerfile
The process for raising the version bump PR is: 
* Query docker hub for a list of versions and find the most recent one.
* Grep the Dockerfile for the existing version.
* If they are different, create a file `Dockerfile-new` with the new version in the `FROM` command and the rest of the Dockerfile unchanged.
* Rename `Dockerfile-new` to `Dockerfile`
* Repeat the steps for `Dockerfile-prod`
* Commit, push and create the pull request
I'm using the plugin-updates node because that already has github cli on it to make raising the PR easy and it's already set up to do signed commits. It didn't have `jq` installed so I've added that in as well.
There is an example PR showing the changes you would see https://github.com/nationalarchives/tdr-jenkins/pull/220
> Create PR for version updates

- Jenkinsfile-build-nodes
- docker/Dockerfile
- docker/Dockerfile-prod
Leaving as draft whilst monitor Jenkins instances with this change deployed to make sure no issues. 
Will allow quick rollback from `main` branch if there are any problems.
> Tdr 1354 upgrade jenkins version

- docker/Dockerfile
- docker/Dockerfile-prod
Changes already deployed to both Jenkins instances
> Tdr 1354 remove override config

- docker/Dockerfile
- docker/Dockerfile-prod
These changes have already been deployed
> Ecr alerts jenkins nodes

- docker/nodes/aws/Dockerfile
- docker/nodes/npm/Dockerfile
- docker/nodes/plugin-updates/Dockerfile
- docker/nodes/postgres/Dockerfile
- docker/nodes/terraform/Dockerfile
- docker/nodes/transfer-frontend/Dockerfile
These changes have already been deployed
> Upgrade busy box

- terraform/root_integration.tf
This adds the policy created in https://github.com/nationalarchives/tdr-terraform-modules/pull/158
to the JenkinsAppTaskRole.
> Add policy for lambda checks.

- README.md
- terraform/.terraform.lock.hcl
- terraform/root_integration.tf
- terraform/root_production.tf
- terraform/versions.tf
> Tdr 1188 terraform upgrade v1

- docker/nodes/npm/Dockerfile
- docker/nodes/plugin-updates/Dockerfile
- docker/nodes/postgres/Dockerfile
- docker/nodes/terraform-latest/Dockerfile
- docker/nodes/terraform/Dockerfile
- docker/nodes/transfer-frontend/Dockerfile
> Expat ecr vuln

- docker/nodes/npm/Dockerfile
- docker/nodes/plugin-updates/Dockerfile
- docker/nodes/postgres/Dockerfile
- docker/nodes/terraform-latest/Dockerfile
- docker/nodes/terraform/Dockerfile
- docker/nodes/transfer-frontend/Dockerfile
Force upgrade of library until alpine updated
Already deployed
> Vulnerability identified in library

- docker/nodes/aws/Dockerfile
> Aws node update libretls

- docker/nodes/aws/Dockerfile
- docker/nodes/npm/Dockerfile
- docker/nodes/plugin-updates/Dockerfile
- docker/nodes/postgres/Dockerfile
- docker/nodes/terraform-latest/Dockerfile
- docker/nodes/terraform/Dockerfile
- docker/nodes/transfer-frontend/Dockerfile
Already deployed
Manually upgrade 'zlib' library to resolve vulnerability until alpine is updated
> Upgrade 'zlib' library on Jenkins image nodes

- docker/nodes/postgres/Dockerfile
> Upgrade 'nss' library

- docker/nodes/aws/Dockerfile
- docker/nodes/npm/Dockerfile
- docker/nodes/plugin-updates/Dockerfile
- docker/nodes/postgres/Dockerfile
- docker/nodes/terraform-latest/Dockerfile
- docker/nodes/terraform/Dockerfile
- docker/nodes/transfer-frontend/Dockerfile
> Upgrade git
